package kr.co.cking.drawing.domain;

public enum DrawingVerificationFailureCode {

    SNAPSHOT_INTEGRITY_FAILED,
    DRAWING_CONTRACT_MISMATCH,
    STORED_INPUT_INTEGRITY_FAILED,
    STORED_RESULT_INTEGRITY_FAILED,
    INSUFFICIENT_CANDIDATES,
    UNSUPPORTED_ALGORITHM_VERSION,
    REPLAY_RESULT_INVALID,
    VERIFICATION_EXECUTION_FAILED
}
