package kr.co.cking.abuse.domain;

/** Feature Store가 측정하고 Rule Engine이 임계치와 비교하는 지표 이름이다. */
public enum AbuseMetric {
    MISSION_REQUEST_COUNT,
    DUPLICATE_MISSION_FAILURE_COUNT,
    ENTRY_REQUEST_COUNT,
    INSUFFICIENT_BALANCE_FAILURE_COUNT,
    INSUFFICIENT_BALANCE_CONSECUTIVE_COUNT,
    DISTINCT_REQUEST_ID_COUNT,
    RAPID_EARN_SPEND_PAIR_COUNT,
    FAILURE_COUNT,
    FAILURE_CONSECUTIVE_COUNT,
    DISTINCT_FAILURE_TYPE_COUNT
}
